###
# @name get-csv-files
GET {{base_url}}/csv-manager/
# ?limit=2
# &offset=2
# &is_store=true
# &ordering=-created_at

###
# @name create-csv-file
POST {{base_url}}/csv-manager/
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="SalesJan2009.csv"
Content-Type: application/octet-stream

< ./samples_csv/SalesJan2009.csv
--MyBoundary
Content-Disposition: form-data; name="ProspectId"

1
--MyBoundary--

###
# @name retrieve-csv-file
GET {{base_url}}/csv-manager/1/

###
# @name patch-csv-file
PATCH {{base_url}}/csv-manager/1/

{
    "is_store": true
}

###
# @name delete-csv-file
DELETE {{base_url}}/csv-manager/2/

###
# @name read-csv-data
GET {{base_url}}/csv-manager/data/SalesJan2009/
# ?limit=40
# &offset=80
# ?ordering=-id
# &Price=1200
# ?Price=1200
# ?Name=pamela
